import express from 'express';
import cors from 'cors';

const app = express();
const PORT = 8003;

app.use(cors());
app.use(express.json());

// Health check
app.get('/health', (req, res) => {
  res.json({ status: 'healthy', service: 'report-generation' });
});

// POST /generate-report - Mock report generation
app.post('/generate-report', (req, res) => {
  const {
    claim_id,
    damage_type,
    severity_score,
    estimated_cost,
    fraud_score,
    vehicle_info,
    incident_description
  } = req.body;

  console.log(`[Report Generation] Generating report for claim: ${claim_id}`);

  // Simulate processing delay
  setTimeout(() => {
    const reportId = `RPT-${claim_id}-${Date.now()}`;

    res.json({
      reportId,
      reportUrl: `https://mock-reports.example.com/reports/${reportId}.pdf`,
      reportText: `
INSURANCE CLAIM ASSESSMENT REPORT
================================

Claim ID: ${claim_id}
Generated: ${new Date().toISOString()}

VEHICLE INFORMATION
-------------------
Registration: ${vehicle_info?.vehicleNumber || 'N/A'}
Make: ${vehicle_info?.make || 'Not specified'}
Model: ${vehicle_info?.model || 'Not specified'}

INCIDENT DESCRIPTION
--------------------
${incident_description || 'No description provided'}

DAMAGE ASSESSMENT
-----------------
Damage Type: ${damage_type || 'Unknown'}
Severity Score: ${(severity_score * 100).toFixed(1)}%

COST ESTIMATION
---------------
Estimated Repair Cost: ₹${estimated_cost?.toLocaleString() || 'N/A'}

FRAUD ANALYSIS
--------------
Risk Score: ${(fraud_score * 100).toFixed(1)}%
Status: ${fraud_score < 0.2 ? 'LOW RISK - Proceed with claim' : 'MEDIUM RISK - Manual review recommended'}

RECOMMENDATION
--------------
Based on the AI analysis, this claim ${fraud_score < 0.2 ? 'is recommended for approval' : 'requires additional manual review'}.

---
This report was generated by AI Insurance Assessment System.
      `.trim()
    });
  }, 600);
});

app.listen(PORT, () => {
  console.log(`[Mock] Report Generation Service running on http://localhost:${PORT}`);
});
